//! Canonical op_id registry and mapping from Coelanox OpType (or op name) to op_id.
//!
//! Single source of truth: see docs/op_ids.md for the full table. Op_ids are stable;
//! new ops get new ids, old ones are not renumbered. Custom range **256–65535** is for
//! producer-defined ops (no collision with canonical set).

/// Coelanox OpType: symbolic type for IR nodes. Maps to canonical op_id in CLF.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
#[non_exhaustive]
pub enum OpType {
    // Reserved / unknown
    Unknown,
    // Arithmetic 1–9
    Add,
    Subtract,
    Multiply,
    Divide,
    // Activations 10–19
    Relu,
    Sigmoid,
    Tanh,
    Softmax,
    LogSoftmax,
    Gelu,
    Swish,
    // Math 20–29
    Sqrt,
    Pow,
    Cos,
    Sin,
    Exp,
    Log,
    // Conv/pool/norm 30–39
    Convolution,
    MaxPool,
    AvgPool,
    GlobalMaxPool,
    GlobalAvgPool,
    BatchNorm,
    LayerNorm,
    Dropout,
    // Tensor manip 40–49
    Reshape,
    Transpose,
    Permute,
    Concatenate,
    Split,
    Slice,
    Gather,
    Scatter,
    // Linear 50–59
    MatMul,
    Gemm,
    // Reductions 60–69
    ReduceSum,
    ReduceMean,
    ReduceMax,
    ReduceMin,
    ReduceProd,
    // Comparisons 80–89
    Equal,
    NotEqual,
    Greater,
    GreaterEqual,
    Less,
    LessEqual,
    // Logical 90–99
    And,
    Or,
    Not,
    /// Custom or reserved; op_id 0 or 100+ per agreement.
    Custom(u16),
}

/// Maps Coelanox OpType to canonical CLF op_id (u16).
/// Used by the packager when generating code from a CLF backend.
#[must_use]
pub fn op_type_to_clf_id(op_type: OpType) -> u16 {
    match op_type {
        OpType::Unknown | OpType::Custom(0) => 0,
        OpType::Custom(id) => id,
        OpType::Add => 1,
        OpType::Subtract => 2,
        OpType::Multiply => 3,
        OpType::Divide => 4,
        OpType::Relu => 10,
        OpType::Sigmoid => 11,
        OpType::Tanh => 12,
        OpType::Softmax => 13,
        OpType::LogSoftmax => 14,
        OpType::Gelu => 15,
        OpType::Swish => 16,
        OpType::Sqrt => 20,
        OpType::Pow => 21,
        OpType::Cos => 22,
        OpType::Sin => 23,
        OpType::Exp => 24,
        OpType::Log => 25,
        OpType::Convolution => 30,
        OpType::MaxPool => 31,
        OpType::AvgPool => 32,
        OpType::GlobalMaxPool => 33,
        OpType::GlobalAvgPool => 34,
        OpType::BatchNorm => 35,
        OpType::LayerNorm => 36,
        OpType::Dropout => 37,
        OpType::Reshape => 40,
        OpType::Transpose => 41,
        OpType::Permute => 42,
        OpType::Concatenate => 43,
        OpType::Split => 44,
        OpType::Slice => 45,
        OpType::Gather => 46,
        OpType::Scatter => 47,
        OpType::MatMul => 50,
        OpType::Gemm => 51,
        OpType::ReduceSum => 60,
        OpType::ReduceMean => 61,
        OpType::ReduceMax => 62,
        OpType::ReduceMin => 63,
        OpType::ReduceProd => 64,
        OpType::Equal => 80,
        OpType::NotEqual => 81,
        OpType::Greater => 82,
        OpType::GreaterEqual => 83,
        OpType::Less => 84,
        OpType::LessEqual => 85,
        OpType::And => 90,
        OpType::Or => 91,
        OpType::Not => 92,
    }
}

/// Reverse map: op_id → OpType (for tooling / diagnostics). Unknown op_ids map to Custom(id).
#[must_use]
pub fn clf_id_to_op_type(op_id: u16) -> OpType {
    match op_id {
        0 => OpType::Unknown,
        1 => OpType::Add,
        2 => OpType::Subtract,
        3 => OpType::Multiply,
        4 => OpType::Divide,
        10 => OpType::Relu,
        11 => OpType::Sigmoid,
        12 => OpType::Tanh,
        13 => OpType::Softmax,
        14 => OpType::LogSoftmax,
        15 => OpType::Gelu,
        16 => OpType::Swish,
        20 => OpType::Sqrt,
        21 => OpType::Pow,
        22 => OpType::Cos,
        23 => OpType::Sin,
        24 => OpType::Exp,
        25 => OpType::Log,
        30 => OpType::Convolution,
        31 => OpType::MaxPool,
        32 => OpType::AvgPool,
        33 => OpType::GlobalMaxPool,
        34 => OpType::GlobalAvgPool,
        35 => OpType::BatchNorm,
        36 => OpType::LayerNorm,
        37 => OpType::Dropout,
        40 => OpType::Reshape,
        41 => OpType::Transpose,
        42 => OpType::Permute,
        43 => OpType::Concatenate,
        44 => OpType::Split,
        45 => OpType::Slice,
        46 => OpType::Gather,
        47 => OpType::Scatter,
        50 => OpType::MatMul,
        51 => OpType::Gemm,
        60 => OpType::ReduceSum,
        61 => OpType::ReduceMean,
        62 => OpType::ReduceMax,
        63 => OpType::ReduceMin,
        64 => OpType::ReduceProd,
        80 => OpType::Equal,
        81 => OpType::NotEqual,
        82 => OpType::Greater,
        83 => OpType::GreaterEqual,
        84 => OpType::Less,
        85 => OpType::LessEqual,
        90 => OpType::And,
        91 => OpType::Or,
        92 => OpType::Not,
        id => OpType::Custom(id),
    }
}
